import { chromium } from 'playwright';
import { pathToFileURL } from 'url';
import { resolve } from 'path';
const file = pathToFileURL(resolve('./messages-redesign.html')).href;
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 920 }, deviceScaleFactor: 1 });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', e => errors.push('pageerror: ' + e.message));
page.on('console', m => { if (m.type() === 'error') errors.push('console.error: ' + m.text()); });
await page.goto(file);
await page.waitForLoadState('networkidle');
await page.waitForTimeout(400);
// default is D. Trigger ⌘K via real keyboard (Control on headless chromium).
await page.keyboard.press('Control+k');
await page.waitForTimeout(300);
const paletteVisible = await page.locator('text=Search messages, people, or run a command').isVisible();
console.log('palette via Ctrl+K visible:', paletteVisible);
await page.screenshot({ path: '_shots/msg-12-D-cmdk.png' });
console.log('✓ msg-12-D-cmdk');
await page.keyboard.press('Escape');
await page.waitForTimeout(200);
const afterEsc = await page.locator('text=Search messages, people, or run a command').isVisible();
console.log('palette after Esc visible:', afterEsc);
await page.locator('main button[title="Command palette (⌘K)"]').first().click();
await page.waitForTimeout(200);
const viaBtn = await page.locator('text=Search messages, people, or run a command').isVisible();
console.log('palette via header button visible:', viaBtn);
console.log(errors.length ? '\n--- errors ---\n' + errors.join('\n') : '\nno console/page errors');
await browser.close();
