import React from 'react';
import { X } from 'lucide-react';

export type AIProvenanceSource =
  | 'claude'
  | 'gemini'
  | 'gpt-4'
  | 'gpt-4o'
  | 'pulse-ai'
  | (string & {});

export type AIProvenanceKind =
  | 'summary'
  | 'draft'
  | 'suggestion'
  | 'action'
  | 'transcription'
  | 'analysis'
  | 'mediation'
  | 'phrase'
  | 'recap'
  | 'briefing'
  | (string & {});

export interface AIProvenanceTagProps {
  source: AIProvenanceSource;
  kind: AIProvenanceKind;
  onDismiss?: () => void;
  showDot?: boolean;
  className?: string;
}

const formatToken = (raw: string): string => raw.replace(/-/g, ' ');

export const AIProvenanceTag: React.FC<AIProvenanceTagProps> = ({
  source,
  kind,
  onDismiss,
  showDot = true,
  className = '',
}) => {
  const label = `${formatToken(source)} · ${formatToken(kind)}`;
  const ariaLabel = `AI generated by ${source}: ${kind}`;

  return (
    <span
      role="note"
      aria-label={ariaLabel}
      className={`inline-flex items-center gap-1.5 bg-rose-500/[0.10] dark:bg-rose-500/[0.15] text-rose-600 dark:text-rose-400 font-mono text-[11px] font-medium uppercase tracking-[0.1em] px-2 py-1 rounded ${className}`}
    >
      {showDot && (
        <span
          aria-hidden="true"
          className="inline-block w-[6px] h-[6px] rounded-full bg-rose-500 shadow-[0_0_8px_rgba(244,63,94,0.5)]"
        />
      )}
      <span>{label}</span>
      {onDismiss && (
        <button
          type="button"
          onClick={onDismiss}
          aria-label={`Dismiss AI ${kind}`}
          className="ml-0.5 -mr-1 inline-flex items-center justify-center w-4 h-4 rounded-sm text-rose-600/70 dark:text-rose-400/70 hover:text-rose-600 dark:hover:text-rose-400 hover:bg-rose-500/[0.15] transition-colors"
        >
          <X className="w-3 h-3" />
        </button>
      )}
    </span>
  );
};
