// Step 2 schema for the "Build something" decision frame.
//
// Captures the inputs needed to scope a feature spec, project kickoff, or
// one-off build: what is being built, who it's for, the operator's hypothesis
// about why it matters, the acceptance signal that proves it worked, the
// target ship date, and any workspace stakeholders involved.
//
// The frame's "decision moment" is the upstream scoping call (yes/no/scope),
// not the final ship. Tasks generated by suggestTasks reflect that. A
// kickoff/scoping task near the start carries isDecisionMoment.
//
// Consumed by buildFrame.tsx (Step2Form, validateStep2, suggestTasks,
// derivers) and persisted into WizardState.step2 keyed by frameId.

export interface BuildStep2 {
  /** What is being built. Free-form noun phrase, e.g. "Email digest scheduler". */
  whatBuilding: string;

  /** Who the build is for. Free-form audience description,
   *  e.g. "Product managers running weekly reviews". */
  forWhom: string;

  /** Operator's hypothesis in "I think X because Y" framing. */
  hypothesis: string;

  /** Concrete acceptance signal. "We'll know it's working when..." */
  acceptanceSignal: string;

  /** ISO date string (YYYY-MM-DD) the build should ship by.
   *  Defaults to today + 21 days. */
  targetShipDate: string;

  /** Workspace member ids brought in on the decision. Optional. */
  stakeholders: string[];
}
