import React, { useState } from 'react';
import { useWorkspace } from './WorkspaceContext';
import { messageChannelService } from '../../../services/messageChannelService';
import { ragService } from '../../../services/ragService';
import './ShareToChannelModal.css';

interface ShareToChannelModalProps {
  title: string;
  content: string;
  onClose: () => void;
}

const ShareToChannelModal: React.FC<ShareToChannelModalProps> = ({ title, content, onClose }) => {
  const { teamChannels, currentUser, apiKeys } = useWorkspace();
  const [selectedChannelId, setSelectedChannelId] = useState('');
  const [isSending, setIsSending] = useState(false);
  const [isSavingToKB, setIsSavingToKB] = useState(false);
  const [sent, setSent] = useState(false);
  const [savedToKB, setSavedToKB] = useState(false);

  const handleShareToChannel = async () => {
    if (!selectedChannelId || !currentUser) return;
    setIsSending(true);
    try {
      const formattedContent = `**AI Output: ${title}**\n\n${content}\n\n---\n*Generated by Pulse AI Lab*`;
      await messageChannelService.sendMessage(selectedChannelId, currentUser.id, formattedContent);
      setSent(true);
    } catch (err) {
      console.error('Failed to share to channel:', err);
    } finally {
      setIsSending(false);
    }
  };

  const handleSaveToKnowledgeBase = async () => {
    if (!currentUser || !apiKeys.gemini) return;
    setIsSavingToKB(true);
    try {
      await ragService.ingestTextDocument(
        apiKeys.gemini,
        currentUser.id,
        `AI Lab: ${title} — ${new Date().toLocaleDateString()}`,
        content,
        'text'
      );
      setSavedToKB(true);
    } catch (err) {
      console.error('Failed to save to Knowledge Base:', err);
    } finally {
      setIsSavingToKB(false);
    }
  };

  return (
    <div className="share-modal-overlay" onClick={onClose}>
      <div className="share-modal" onClick={e => e.stopPropagation()}>
        <div className="share-modal-header">
          <h3>
            <i className="fa-solid fa-share-nodes"></i>
            Share Output
          </h3>
          <button type="button" className="share-modal-close" onClick={onClose} aria-label="Close">
            <i className="fa-solid fa-xmark"></i>
          </button>
        </div>

        <div className="share-modal-body">
          <div className="share-preview">
            <span className="share-preview-label">
              <i className="fa-solid fa-file-lines"></i>
              {title}
            </span>
            <p className="share-preview-text">{content.slice(0, 120)}{content.length > 120 ? '...' : ''}</p>
          </div>

          {/* Share to Channel */}
          <div className="share-section">
            <h4>Share to Channel</h4>
            {teamChannels.length === 0 ? (
              <p className="share-empty">No channels available. Join a workspace to share.</p>
            ) : (
              <div className="share-channel-list">
                {teamChannels.map(ch => (
                  <button
                    key={ch.id}
                    type="button"
                    className={`share-channel-item ${selectedChannelId === ch.id ? 'active' : ''}`}
                    onClick={() => setSelectedChannelId(ch.id)}
                  >
                    <i className="fa-solid fa-hashtag"></i>
                    <span>{ch.name}</span>
                    {selectedChannelId === ch.id && <i className="fa-solid fa-check"></i>}
                  </button>
                ))}
              </div>
            )}
            {teamChannels.length > 0 && (
              <button
                type="button"
                className={`share-btn share-btn-primary ${sent ? 'share-btn-success' : ''}`}
                onClick={handleShareToChannel}
                disabled={!selectedChannelId || isSending || sent}
              >
                {sent ? (
                  <><i className="fa-solid fa-check"></i> Sent to Channel</>
                ) : isSending ? (
                  <><i className="fa-solid fa-spinner fa-spin"></i> Sending...</>
                ) : (
                  <><i className="fa-solid fa-paper-plane"></i> Send to Channel</>
                )}
              </button>
            )}
          </div>

          {/* Save to Knowledge Base */}
          <div className="share-section">
            <h4>Save to Knowledge Base</h4>
            <p className="share-section-desc">Save this AI output for future retrieval and Q&A.</p>
            <button
              type="button"
              className={`share-btn share-btn-secondary ${savedToKB ? 'share-btn-success' : ''}`}
              onClick={handleSaveToKnowledgeBase}
              disabled={!apiKeys.gemini || isSavingToKB || savedToKB}
            >
              {savedToKB ? (
                <><i className="fa-solid fa-check"></i> Saved to Knowledge Base</>
              ) : isSavingToKB ? (
                <><i className="fa-solid fa-spinner fa-spin"></i> Saving...</>
              ) : (
                <><i className="fa-solid fa-database"></i> Save to Knowledge Base</>
              )}
            </button>
            {!apiKeys.gemini && (
              <p className="share-warning">Gemini API key required. Add it in Settings.</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default ShareToChannelModal;
